export KEY_NAME="join-2"
export PUBLIC_URL="http://89.169.110.250:8000"
export P2P_EXTERNAL_ADDRESS="tcp://89.169.110.250:5000"
export SYNC_WITH_SNAPSHOTS="false"
export DAPI_API__POC_CALLBACK_URL="http://api:9100"
export CHAIN_ID="gonka-testnet"
export HF_HOME="/srv/dai/cache/"
export TESTNET_BASE_DIR="/srv/dai/"

python3 launch.py --mode join --branch origin/testnet/main --chainid "$CHAIN_ID"
