// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/devshard_escrow.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DevshardEscrow struct {
	Id         uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator    string   `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount     uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Slots      []string `protobuf:"bytes,4,rep,name=slots,proto3" json:"slots,omitempty"`
	EpochIndex uint64   `protobuf:"varint,5,opt,name=epoch_index,json=epochIndex,proto3" json:"epoch_index,omitempty"`
	AppHash    string   `protobuf:"bytes,6,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
	Settled    bool     `protobuf:"varint,7,opt,name=settled,proto3" json:"settled,omitempty"`
	TokenPrice uint64   `protobuf:"varint,8,opt,name=token_price,json=tokenPrice,proto3" json:"token_price,omitempty"`
	ModelId    string   `protobuf:"bytes,9,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
}

func (m *DevshardEscrow) Reset()         { *m = DevshardEscrow{} }
func (m *DevshardEscrow) String() string { return proto.CompactTextString(m) }
func (*DevshardEscrow) ProtoMessage()    {}
func (*DevshardEscrow) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb886b60751f999, []int{0}
}
func (m *DevshardEscrow) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DevshardEscrow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DevshardEscrow.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DevshardEscrow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevshardEscrow.Merge(m, src)
}
func (m *DevshardEscrow) XXX_Size() int {
	return m.Size()
}
func (m *DevshardEscrow) XXX_DiscardUnknown() {
	xxx_messageInfo_DevshardEscrow.DiscardUnknown(m)
}

var xxx_messageInfo_DevshardEscrow proto.InternalMessageInfo

func (m *DevshardEscrow) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DevshardEscrow) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *DevshardEscrow) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *DevshardEscrow) GetSlots() []string {
	if m != nil {
		return m.Slots
	}
	return nil
}

func (m *DevshardEscrow) GetEpochIndex() uint64 {
	if m != nil {
		return m.EpochIndex
	}
	return 0
}

func (m *DevshardEscrow) GetAppHash() string {
	if m != nil {
		return m.AppHash
	}
	return ""
}

func (m *DevshardEscrow) GetSettled() bool {
	if m != nil {
		return m.Settled
	}
	return false
}

func (m *DevshardEscrow) GetTokenPrice() uint64 {
	if m != nil {
		return m.TokenPrice
	}
	return 0
}

func (m *DevshardEscrow) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

type DevshardHostEpochStats struct {
	Participant          string `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
	EpochIndex           uint64 `protobuf:"varint,2,opt,name=epoch_index,json=epochIndex,proto3" json:"epoch_index,omitempty"`
	Missed               uint32 `protobuf:"varint,3,opt,name=missed,proto3" json:"missed,omitempty"`
	Invalid              uint32 `protobuf:"varint,4,opt,name=invalid,proto3" json:"invalid,omitempty"`
	Cost                 uint64 `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	RequiredValidations  uint32 `protobuf:"varint,6,opt,name=required_validations,json=requiredValidations,proto3" json:"required_validations,omitempty"`
	CompletedValidations uint32 `protobuf:"varint,7,opt,name=completed_validations,json=completedValidations,proto3" json:"completed_validations,omitempty"`
	EscrowCount          uint32 `protobuf:"varint,8,opt,name=escrow_count,json=escrowCount,proto3" json:"escrow_count,omitempty"`
}

func (m *DevshardHostEpochStats) Reset()         { *m = DevshardHostEpochStats{} }
func (m *DevshardHostEpochStats) String() string { return proto.CompactTextString(m) }
func (*DevshardHostEpochStats) ProtoMessage()    {}
func (*DevshardHostEpochStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb886b60751f999, []int{1}
}
func (m *DevshardHostEpochStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DevshardHostEpochStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DevshardHostEpochStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DevshardHostEpochStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevshardHostEpochStats.Merge(m, src)
}
func (m *DevshardHostEpochStats) XXX_Size() int {
	return m.Size()
}
func (m *DevshardHostEpochStats) XXX_DiscardUnknown() {
	xxx_messageInfo_DevshardHostEpochStats.DiscardUnknown(m)
}

var xxx_messageInfo_DevshardHostEpochStats proto.InternalMessageInfo

func (m *DevshardHostEpochStats) GetParticipant() string {
	if m != nil {
		return m.Participant
	}
	return ""
}

func (m *DevshardHostEpochStats) GetEpochIndex() uint64 {
	if m != nil {
		return m.EpochIndex
	}
	return 0
}

func (m *DevshardHostEpochStats) GetMissed() uint32 {
	if m != nil {
		return m.Missed
	}
	return 0
}

func (m *DevshardHostEpochStats) GetInvalid() uint32 {
	if m != nil {
		return m.Invalid
	}
	return 0
}

func (m *DevshardHostEpochStats) GetCost() uint64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *DevshardHostEpochStats) GetRequiredValidations() uint32 {
	if m != nil {
		return m.RequiredValidations
	}
	return 0
}

func (m *DevshardHostEpochStats) GetCompletedValidations() uint32 {
	if m != nil {
		return m.CompletedValidations
	}
	return 0
}

func (m *DevshardHostEpochStats) GetEscrowCount() uint32 {
	if m != nil {
		return m.EscrowCount
	}
	return 0
}

type DevshardSettlementHostStats struct {
	SlotId               uint32 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Missed               uint32 `protobuf:"varint,2,opt,name=missed,proto3" json:"missed,omitempty"`
	Invalid              uint32 `protobuf:"varint,3,opt,name=invalid,proto3" json:"invalid,omitempty"`
	Cost                 uint64 `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	RequiredValidations  uint32 `protobuf:"varint,5,opt,name=required_validations,json=requiredValidations,proto3" json:"required_validations,omitempty"`
	CompletedValidations uint32 `protobuf:"varint,6,opt,name=completed_validations,json=completedValidations,proto3" json:"completed_validations,omitempty"`
}

func (m *DevshardSettlementHostStats) Reset()         { *m = DevshardSettlementHostStats{} }
func (m *DevshardSettlementHostStats) String() string { return proto.CompactTextString(m) }
func (*DevshardSettlementHostStats) ProtoMessage()    {}
func (*DevshardSettlementHostStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb886b60751f999, []int{2}
}
func (m *DevshardSettlementHostStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DevshardSettlementHostStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DevshardSettlementHostStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DevshardSettlementHostStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevshardSettlementHostStats.Merge(m, src)
}
func (m *DevshardSettlementHostStats) XXX_Size() int {
	return m.Size()
}
func (m *DevshardSettlementHostStats) XXX_DiscardUnknown() {
	xxx_messageInfo_DevshardSettlementHostStats.DiscardUnknown(m)
}

var xxx_messageInfo_DevshardSettlementHostStats proto.InternalMessageInfo

func (m *DevshardSettlementHostStats) GetSlotId() uint32 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *DevshardSettlementHostStats) GetMissed() uint32 {
	if m != nil {
		return m.Missed
	}
	return 0
}

func (m *DevshardSettlementHostStats) GetInvalid() uint32 {
	if m != nil {
		return m.Invalid
	}
	return 0
}

func (m *DevshardSettlementHostStats) GetCost() uint64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *DevshardSettlementHostStats) GetRequiredValidations() uint32 {
	if m != nil {
		return m.RequiredValidations
	}
	return 0
}

func (m *DevshardSettlementHostStats) GetCompletedValidations() uint32 {
	if m != nil {
		return m.CompletedValidations
	}
	return 0
}

type DevshardSlotSignature struct {
	SlotId    uint32 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *DevshardSlotSignature) Reset()         { *m = DevshardSlotSignature{} }
func (m *DevshardSlotSignature) String() string { return proto.CompactTextString(m) }
func (*DevshardSlotSignature) ProtoMessage()    {}
func (*DevshardSlotSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb886b60751f999, []int{3}
}
func (m *DevshardSlotSignature) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DevshardSlotSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DevshardSlotSignature.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DevshardSlotSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevshardSlotSignature.Merge(m, src)
}
func (m *DevshardSlotSignature) XXX_Size() int {
	return m.Size()
}
func (m *DevshardSlotSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_DevshardSlotSignature.DiscardUnknown(m)
}

var xxx_messageInfo_DevshardSlotSignature proto.InternalMessageInfo

func (m *DevshardSlotSignature) GetSlotId() uint32 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *DevshardSlotSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*DevshardEscrow)(nil), "inference.inference.DevshardEscrow")
	proto.RegisterType((*DevshardHostEpochStats)(nil), "inference.inference.DevshardHostEpochStats")
	proto.RegisterType((*DevshardSettlementHostStats)(nil), "inference.inference.DevshardSettlementHostStats")
	proto.RegisterType((*DevshardSlotSignature)(nil), "inference.inference.DevshardSlotSignature")
}

func init() {
	proto.RegisterFile("inference/inference/devshard_escrow.proto", fileDescriptor_1fb886b60751f999)
}

var fileDescriptor_1fb886b60751f999 = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x97, 0xac, 0x4d, 0x5b, 0x77, 0xdd, 0xc1, 0xeb, 0x8a, 0x11, 0x28, 0x94, 0x9e, 0xca,
	0xa5, 0x13, 0x9a, 0xf8, 0x02, 0xc0, 0xa4, 0xf5, 0x02, 0x28, 0x95, 0x38, 0x70, 0x89, 0x3c, 0xdb,
	0x2c, 0x16, 0x49, 0x6c, 0xec, 0xb7, 0x63, 0x7c, 0x0b, 0x3e, 0x08, 0x1f, 0x84, 0xe3, 0x8e, 0x1c,
	0x51, 0xcb, 0xa7, 0xe0, 0x84, 0xec, 0x34, 0x6d, 0x55, 0xa8, 0x84, 0xb8, 0xbd, 0xcf, 0xf3, 0xfe,
	0x49, 0xde, 0x9f, 0x6d, 0xf4, 0x44, 0x96, 0xef, 0x85, 0x11, 0x25, 0x13, 0x67, 0x9b, 0x88, 0x8b,
	0x1b, 0x9b, 0x51, 0xc3, 0x53, 0x61, 0x99, 0x51, 0x9f, 0x26, 0xda, 0x28, 0x50, 0xf8, 0x64, 0x5d,
	0x30, 0x59, 0x47, 0xa3, 0x5f, 0x01, 0x3a, 0x7e, 0xb9, 0x2a, 0xbf, 0xf0, 0xd5, 0xf8, 0x18, 0x85,
	0x92, 0x93, 0x60, 0x18, 0x8c, 0x1b, 0x49, 0x28, 0x39, 0x26, 0xa8, 0xc5, 0x8c, 0xa0, 0xa0, 0x0c,
	0x09, 0x87, 0xc1, 0xb8, 0x93, 0xd4, 0x12, 0x0f, 0x50, 0x44, 0x0b, 0x35, 0x2f, 0x81, 0x1c, 0xfa,
	0xea, 0x95, 0xc2, 0x7d, 0xd4, 0xb4, 0xb9, 0x02, 0x4b, 0x1a, 0xc3, 0xc3, 0x71, 0x27, 0xa9, 0x04,
	0x7e, 0x84, 0xba, 0x42, 0x2b, 0x96, 0xa5, 0xb2, 0xe4, 0xe2, 0x96, 0x34, 0x7d, 0x0b, 0xf2, 0xd6,
	0xd4, 0x39, 0xf8, 0x3e, 0x6a, 0x53, 0xad, 0xd3, 0x8c, 0xda, 0x8c, 0x44, 0xd5, 0x97, 0xa8, 0xd6,
	0x97, 0xd4, 0x66, 0xee, 0x1f, 0xac, 0x00, 0xc8, 0x05, 0x27, 0xad, 0x61, 0x30, 0x6e, 0x27, 0xb5,
	0x74, 0x53, 0x41, 0x7d, 0x10, 0x65, 0xaa, 0x8d, 0x64, 0x82, 0xb4, 0xab, 0xa9, 0xde, 0x7a, 0xe3,
	0x1c, 0x37, 0xb5, 0x50, 0x5c, 0xe4, 0xa9, 0xe4, 0xa4, 0x53, 0x4d, 0xf5, 0x7a, 0xca, 0x47, 0x5f,
	0x43, 0x34, 0xa8, 0x97, 0xbf, 0x54, 0x16, 0x2e, 0xdc, 0xbf, 0xcc, 0x80, 0x82, 0xc5, 0x43, 0xd4,
	0xd5, 0xd4, 0x80, 0x64, 0x52, 0xd3, 0x12, 0x3c, 0x8d, 0x4e, 0xb2, 0x6d, 0xed, 0xae, 0x13, 0xfe,
	0xb1, 0xce, 0x00, 0x45, 0x85, 0xb4, 0x56, 0x70, 0x4f, 0xa7, 0x97, 0xac, 0x94, 0xdb, 0x45, 0x96,
	0x37, 0x34, 0x97, 0x9c, 0x34, 0x7c, 0xa2, 0x96, 0x18, 0xa3, 0x06, 0x53, 0x16, 0x56, 0x68, 0x7c,
	0x8c, 0x9f, 0xa2, 0xbe, 0x11, 0x1f, 0xe7, 0xd2, 0x08, 0x9e, 0xfa, 0x2a, 0x0a, 0x52, 0x95, 0xd6,
	0x03, 0xea, 0x25, 0x27, 0x75, 0xee, 0xed, 0x26, 0x85, 0xcf, 0xd1, 0x29, 0x53, 0x85, 0xce, 0x05,
	0xec, 0xf4, 0xb4, 0x7c, 0x4f, 0x7f, 0x9d, 0xdc, 0x6e, 0x7a, 0x8c, 0x8e, 0xaa, 0xdb, 0x92, 0x32,
	0x7f, 0xa2, 0x6d, 0x5f, 0xdb, 0xad, 0xbc, 0x17, 0xce, 0x1a, 0xfd, 0x0c, 0xd0, 0x83, 0x1a, 0xd7,
	0xcc, 0xe3, 0x2f, 0x44, 0x09, 0x0e, 0x5c, 0xc5, 0xec, 0x1e, 0x6a, 0xb9, 0x93, 0x4e, 0x57, 0xb7,
	0xa7, 0x97, 0x44, 0x4e, 0x4e, 0xf9, 0x16, 0x89, 0x70, 0x1f, 0x89, 0xc3, 0xbf, 0x93, 0x68, 0xfc,
	0x03, 0x89, 0xe6, 0x7f, 0x90, 0x88, 0xf6, 0x93, 0x18, 0xbd, 0x42, 0xa7, 0xeb, 0x2d, 0x73, 0x05,
	0x33, 0x79, 0x5d, 0x52, 0x98, 0x1b, 0xb1, 0x7f, 0xbf, 0x87, 0xa8, 0x63, 0xeb, 0x2a, 0xbf, 0xe2,
	0x51, 0xb2, 0x31, 0x9e, 0xbf, 0xfe, 0xb6, 0x88, 0x83, 0xbb, 0x45, 0x1c, 0xfc, 0x58, 0xc4, 0xc1,
	0x97, 0x65, 0x7c, 0x70, 0xb7, 0x8c, 0x0f, 0xbe, 0x2f, 0xe3, 0x83, 0x77, 0xcf, 0xae, 0x25, 0x64,
	0xf3, 0xab, 0x09, 0x53, 0xc5, 0x99, 0x36, 0x8a, 0xcf, 0x19, 0x58, 0x26, 0x77, 0x1e, 0xf3, 0xed,
	0x56, 0x0c, 0x9f, 0xb5, 0xb0, 0x57, 0x91, 0x7f, 0xcf, 0xe7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x63, 0x8f, 0xea, 0xb3, 0xfc, 0x03, 0x00, 0x00,
}

func (m *DevshardEscrow) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DevshardEscrow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DevshardEscrow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0x4a
	}
	if m.TokenPrice != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.TokenPrice))
		i--
		dAtA[i] = 0x40
	}
	if m.Settled {
		i--
		if m.Settled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.AppHash) > 0 {
		i -= len(m.AppHash)
		copy(dAtA[i:], m.AppHash)
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(len(m.AppHash)))
		i--
		dAtA[i] = 0x32
	}
	if m.EpochIndex != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.EpochIndex))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Slots) > 0 {
		for iNdEx := len(m.Slots) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Slots[iNdEx])
			copy(dAtA[i:], m.Slots[iNdEx])
			i = encodeVarintDevshardEscrow(dAtA, i, uint64(len(m.Slots[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Amount != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DevshardHostEpochStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DevshardHostEpochStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DevshardHostEpochStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EscrowCount != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.EscrowCount))
		i--
		dAtA[i] = 0x40
	}
	if m.CompletedValidations != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.CompletedValidations))
		i--
		dAtA[i] = 0x38
	}
	if m.RequiredValidations != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.RequiredValidations))
		i--
		dAtA[i] = 0x30
	}
	if m.Cost != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.Cost))
		i--
		dAtA[i] = 0x28
	}
	if m.Invalid != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.Invalid))
		i--
		dAtA[i] = 0x20
	}
	if m.Missed != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.Missed))
		i--
		dAtA[i] = 0x18
	}
	if m.EpochIndex != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.EpochIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Participant) > 0 {
		i -= len(m.Participant)
		copy(dAtA[i:], m.Participant)
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(len(m.Participant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DevshardSettlementHostStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DevshardSettlementHostStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DevshardSettlementHostStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CompletedValidations != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.CompletedValidations))
		i--
		dAtA[i] = 0x30
	}
	if m.RequiredValidations != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.RequiredValidations))
		i--
		dAtA[i] = 0x28
	}
	if m.Cost != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.Cost))
		i--
		dAtA[i] = 0x20
	}
	if m.Invalid != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.Invalid))
		i--
		dAtA[i] = 0x18
	}
	if m.Missed != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.Missed))
		i--
		dAtA[i] = 0x10
	}
	if m.SlotId != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.SlotId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DevshardSlotSignature) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DevshardSlotSignature) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DevshardSlotSignature) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if m.SlotId != 0 {
		i = encodeVarintDevshardEscrow(dAtA, i, uint64(m.SlotId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDevshardEscrow(dAtA []byte, offset int, v uint64) int {
	offset -= sovDevshardEscrow(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DevshardEscrow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.Id))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovDevshardEscrow(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.Amount))
	}
	if len(m.Slots) > 0 {
		for _, s := range m.Slots {
			l = len(s)
			n += 1 + l + sovDevshardEscrow(uint64(l))
		}
	}
	if m.EpochIndex != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.EpochIndex))
	}
	l = len(m.AppHash)
	if l > 0 {
		n += 1 + l + sovDevshardEscrow(uint64(l))
	}
	if m.Settled {
		n += 2
	}
	if m.TokenPrice != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.TokenPrice))
	}
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovDevshardEscrow(uint64(l))
	}
	return n
}

func (m *DevshardHostEpochStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Participant)
	if l > 0 {
		n += 1 + l + sovDevshardEscrow(uint64(l))
	}
	if m.EpochIndex != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.EpochIndex))
	}
	if m.Missed != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.Missed))
	}
	if m.Invalid != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.Invalid))
	}
	if m.Cost != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.Cost))
	}
	if m.RequiredValidations != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.RequiredValidations))
	}
	if m.CompletedValidations != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.CompletedValidations))
	}
	if m.EscrowCount != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.EscrowCount))
	}
	return n
}

func (m *DevshardSettlementHostStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SlotId != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.SlotId))
	}
	if m.Missed != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.Missed))
	}
	if m.Invalid != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.Invalid))
	}
	if m.Cost != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.Cost))
	}
	if m.RequiredValidations != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.RequiredValidations))
	}
	if m.CompletedValidations != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.CompletedValidations))
	}
	return n
}

func (m *DevshardSlotSignature) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SlotId != 0 {
		n += 1 + sovDevshardEscrow(uint64(m.SlotId))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovDevshardEscrow(uint64(l))
	}
	return n
}

func sovDevshardEscrow(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDevshardEscrow(x uint64) (n int) {
	return sovDevshardEscrow(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DevshardEscrow) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevshardEscrow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DevshardEscrow: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DevshardEscrow: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slots", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Slots = append(m.Slots, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochIndex", wireType)
			}
			m.EpochIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Settled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Settled = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenPrice", wireType)
			}
			m.TokenPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenPrice |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDevshardEscrow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DevshardHostEpochStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevshardEscrow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DevshardHostEpochStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DevshardHostEpochStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochIndex", wireType)
			}
			m.EpochIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Missed", wireType)
			}
			m.Missed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Missed |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invalid", wireType)
			}
			m.Invalid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Invalid |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cost", wireType)
			}
			m.Cost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cost |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredValidations", wireType)
			}
			m.RequiredValidations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequiredValidations |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedValidations", wireType)
			}
			m.CompletedValidations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletedValidations |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowCount", wireType)
			}
			m.EscrowCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EscrowCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDevshardEscrow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DevshardSettlementHostStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevshardEscrow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DevshardSettlementHostStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DevshardSettlementHostStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotId", wireType)
			}
			m.SlotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Missed", wireType)
			}
			m.Missed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Missed |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invalid", wireType)
			}
			m.Invalid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Invalid |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cost", wireType)
			}
			m.Cost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cost |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredValidations", wireType)
			}
			m.RequiredValidations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequiredValidations |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedValidations", wireType)
			}
			m.CompletedValidations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletedValidations |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDevshardEscrow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DevshardSlotSignature) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevshardEscrow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DevshardSlotSignature: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DevshardSlotSignature: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotId", wireType)
			}
			m.SlotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDevshardEscrow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDevshardEscrow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDevshardEscrow(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDevshardEscrow
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDevshardEscrow
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDevshardEscrow
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDevshardEscrow
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDevshardEscrow
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDevshardEscrow        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDevshardEscrow          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDevshardEscrow = fmt.Errorf("proto: unexpected end of group")
)
