// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/poc_v2.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PoCArtifactV2 represents a single artifact from PoC v2 generation.
type PoCArtifactV2 struct {
	Nonce  int64  `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Vector []byte `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
}

func (m *PoCArtifactV2) Reset()         { *m = PoCArtifactV2{} }
func (m *PoCArtifactV2) String() string { return proto.CompactTextString(m) }
func (*PoCArtifactV2) ProtoMessage()    {}
func (*PoCArtifactV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{0}
}
func (m *PoCArtifactV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoCArtifactV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoCArtifactV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoCArtifactV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoCArtifactV2.Merge(m, src)
}
func (m *PoCArtifactV2) XXX_Size() int {
	return m.Size()
}
func (m *PoCArtifactV2) XXX_DiscardUnknown() {
	xxx_messageInfo_PoCArtifactV2.DiscardUnknown(m)
}

var xxx_messageInfo_PoCArtifactV2 proto.InternalMessageInfo

func (m *PoCArtifactV2) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *PoCArtifactV2) GetVector() []byte {
	if m != nil {
		return m.Vector
	}
	return nil
}

// PoCBatchV2 represents a batch of artifacts from a single node.
type PoCBatchV2 struct {
	ParticipantAddress       string           `protobuf:"bytes,1,opt,name=participant_address,json=participantAddress,proto3" json:"participant_address,omitempty"`
	PocStageStartBlockHeight int64            `protobuf:"varint,2,opt,name=poc_stage_start_block_height,json=pocStageStartBlockHeight,proto3" json:"poc_stage_start_block_height,omitempty"`
	NodeId                   string           `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Artifacts                []*PoCArtifactV2 `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
}

func (m *PoCBatchV2) Reset()         { *m = PoCBatchV2{} }
func (m *PoCBatchV2) String() string { return proto.CompactTextString(m) }
func (*PoCBatchV2) ProtoMessage()    {}
func (*PoCBatchV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{1}
}
func (m *PoCBatchV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoCBatchV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoCBatchV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoCBatchV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoCBatchV2.Merge(m, src)
}
func (m *PoCBatchV2) XXX_Size() int {
	return m.Size()
}
func (m *PoCBatchV2) XXX_DiscardUnknown() {
	xxx_messageInfo_PoCBatchV2.DiscardUnknown(m)
}

var xxx_messageInfo_PoCBatchV2 proto.InternalMessageInfo

func (m *PoCBatchV2) GetParticipantAddress() string {
	if m != nil {
		return m.ParticipantAddress
	}
	return ""
}

func (m *PoCBatchV2) GetPocStageStartBlockHeight() int64 {
	if m != nil {
		return m.PocStageStartBlockHeight
	}
	return 0
}

func (m *PoCBatchV2) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *PoCBatchV2) GetArtifacts() []*PoCArtifactV2 {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

// PoCValidationV2 represents a validator's attestation of a participant's PoC work.
// validated_weight: -1 = reject/fraud, >=0 = accept
type PoCValidationV2 struct {
	ParticipantAddress          string `protobuf:"bytes,1,opt,name=participant_address,json=participantAddress,proto3" json:"participant_address,omitempty"`
	ValidatorParticipantAddress string `protobuf:"bytes,2,opt,name=validator_participant_address,json=validatorParticipantAddress,proto3" json:"validator_participant_address,omitempty"`
	PocStageStartBlockHeight    int64  `protobuf:"varint,3,opt,name=poc_stage_start_block_height,json=pocStageStartBlockHeight,proto3" json:"poc_stage_start_block_height,omitempty"`
	ValidatedWeight             int64  `protobuf:"varint,4,opt,name=validated_weight,json=validatedWeight,proto3" json:"validated_weight,omitempty"`
}

func (m *PoCValidationV2) Reset()         { *m = PoCValidationV2{} }
func (m *PoCValidationV2) String() string { return proto.CompactTextString(m) }
func (*PoCValidationV2) ProtoMessage()    {}
func (*PoCValidationV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{2}
}
func (m *PoCValidationV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoCValidationV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoCValidationV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoCValidationV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoCValidationV2.Merge(m, src)
}
func (m *PoCValidationV2) XXX_Size() int {
	return m.Size()
}
func (m *PoCValidationV2) XXX_DiscardUnknown() {
	xxx_messageInfo_PoCValidationV2.DiscardUnknown(m)
}

var xxx_messageInfo_PoCValidationV2 proto.InternalMessageInfo

func (m *PoCValidationV2) GetParticipantAddress() string {
	if m != nil {
		return m.ParticipantAddress
	}
	return ""
}

func (m *PoCValidationV2) GetValidatorParticipantAddress() string {
	if m != nil {
		return m.ValidatorParticipantAddress
	}
	return ""
}

func (m *PoCValidationV2) GetPocStageStartBlockHeight() int64 {
	if m != nil {
		return m.PocStageStartBlockHeight
	}
	return 0
}

func (m *PoCValidationV2) GetValidatedWeight() int64 {
	if m != nil {
		return m.ValidatedWeight
	}
	return 0
}

func init() {
	proto.RegisterType((*PoCArtifactV2)(nil), "inference.inference.PoCArtifactV2")
	proto.RegisterType((*PoCBatchV2)(nil), "inference.inference.PoCBatchV2")
	proto.RegisterType((*PoCValidationV2)(nil), "inference.inference.PoCValidationV2")
}

func init() { proto.RegisterFile("inference/inference/poc_v2.proto", fileDescriptor_02f1658865fe708f) }

var fileDescriptor_02f1658865fe708f = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4b, 0xe3, 0x40,
	0x18, 0xee, 0x34, 0xdd, 0x2e, 0x9d, 0xdd, 0xa5, 0xcb, 0x74, 0x59, 0x03, 0x6a, 0x08, 0x39, 0xd5,
	0x4b, 0x0a, 0x11, 0x8f, 0x8a, 0x4d, 0x2f, 0x7a, 0x32, 0xa4, 0x50, 0xc1, 0x4b, 0x98, 0xce, 0x4c,
	0x9b, 0xc1, 0x9a, 0x09, 0x93, 0x69, 0xd5, 0x7f, 0xe1, 0xcf, 0xf2, 0xd8, 0x63, 0x8f, 0xd2, 0xfe,
	0x02, 0xff, 0x81, 0x64, 0x52, 0xd2, 0x2a, 0x05, 0xd1, 0xcb, 0xf0, 0x7e, 0x3c, 0xcf, 0xfb, 0xce,
	0xf3, 0xf0, 0x42, 0x9b, 0x27, 0x23, 0x26, 0x59, 0x42, 0x58, 0x67, 0x13, 0xa5, 0x82, 0x44, 0x33,
	0xcf, 0x4d, 0xa5, 0x50, 0x02, 0xb5, 0xca, 0xba, 0x5b, 0x46, 0xce, 0x29, 0xfc, 0x13, 0x88, 0x5e,
	0x57, 0x2a, 0x3e, 0xc2, 0x44, 0x0d, 0x3c, 0xf4, 0x0f, 0xfe, 0x48, 0x44, 0x42, 0x98, 0x09, 0x6c,
	0xd0, 0x36, 0xc2, 0x22, 0x41, 0xff, 0x61, 0x7d, 0xc6, 0x88, 0x12, 0xd2, 0xac, 0xda, 0xa0, 0xfd,
	0x3b, 0x5c, 0x67, 0xce, 0x02, 0x40, 0x18, 0x88, 0x9e, 0x8f, 0x15, 0x89, 0x07, 0x1e, 0xea, 0xc0,
	0x56, 0x8a, 0xa5, 0xe2, 0x84, 0xa7, 0x38, 0x51, 0x11, 0xa6, 0x54, 0xb2, 0x2c, 0xd3, 0xa3, 0x1a,
	0x21, 0xda, 0x6a, 0x75, 0x8b, 0x0e, 0x3a, 0x83, 0x07, 0xf9, 0x1f, 0x33, 0x85, 0xc7, 0x2c, 0x7f,
	0xa5, 0x8a, 0x86, 0x13, 0x41, 0x6e, 0xa3, 0x98, 0xf1, 0x71, 0xac, 0xf4, 0x36, 0x23, 0x34, 0x53,
	0x41, 0xfa, 0x39, 0xa4, 0x9f, 0x23, 0xfc, 0x1c, 0x70, 0xa1, 0xfb, 0x68, 0x0f, 0xfe, 0x4c, 0x04,
	0x65, 0x11, 0xa7, 0xa6, 0xa1, 0x97, 0xd4, 0xf3, 0xf4, 0x92, 0xa2, 0x73, 0xd8, 0xc0, 0x6b, 0x51,
	0x99, 0x59, 0xb3, 0x8d, 0xf6, 0x2f, 0xcf, 0x71, 0x77, 0x18, 0xe0, 0xbe, 0x53, 0x1f, 0x6e, 0x48,
	0xce, 0x2b, 0x80, 0xcd, 0x40, 0xf4, 0x06, 0x78, 0xc2, 0x29, 0x56, 0x5c, 0x24, 0xdf, 0xd1, 0xe7,
	0xc3, 0xc3, 0x59, 0x31, 0x40, 0xc8, 0x68, 0x17, 0xb5, 0xaa, 0xa9, 0xfb, 0x25, 0x28, 0xf8, 0xba,
	0x47, 0xc6, 0x27, 0x1e, 0x1d, 0xc1, 0xbf, 0xeb, 0xf1, 0x8c, 0x46, 0xf7, 0x05, 0xa7, 0xa6, 0x39,
	0xcd, 0xb2, 0x7e, 0xad, 0xcb, 0xfe, 0xd5, 0xf3, 0xd2, 0x02, 0xf3, 0xa5, 0x05, 0x5e, 0x96, 0x16,
	0x78, 0x5a, 0x59, 0x95, 0xf9, 0xca, 0xaa, 0x2c, 0x56, 0x56, 0xe5, 0xe6, 0x64, 0xcc, 0x55, 0x3c,
	0x1d, 0xba, 0x44, 0xdc, 0x75, 0x52, 0x29, 0xe8, 0x94, 0xa8, 0x8c, 0xf0, 0x0f, 0xe7, 0xf6, 0xb0,
	0x15, 0xab, 0xc7, 0x94, 0x65, 0xc3, 0xba, 0x3e, 0xbd, 0xe3, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x2d, 0x7b, 0x9e, 0x6d, 0x9e, 0x02, 0x00, 0x00,
}

func (m *PoCArtifactV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoCArtifactV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoCArtifactV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Vector) > 0 {
		i -= len(m.Vector)
		copy(dAtA[i:], m.Vector)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.Vector)))
		i--
		dAtA[i] = 0x12
	}
	if m.Nonce != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PoCBatchV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoCBatchV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoCBatchV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Artifacts) > 0 {
		for iNdEx := len(m.Artifacts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Artifacts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPocV2(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.NodeId) > 0 {
		i -= len(m.NodeId)
		copy(dAtA[i:], m.NodeId)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.NodeId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PocStageStartBlockHeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.PocStageStartBlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ParticipantAddress) > 0 {
		i -= len(m.ParticipantAddress)
		copy(dAtA[i:], m.ParticipantAddress)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ParticipantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PoCValidationV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoCValidationV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoCValidationV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValidatedWeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.ValidatedWeight))
		i--
		dAtA[i] = 0x20
	}
	if m.PocStageStartBlockHeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.PocStageStartBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ValidatorParticipantAddress) > 0 {
		i -= len(m.ValidatorParticipantAddress)
		copy(dAtA[i:], m.ValidatorParticipantAddress)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ValidatorParticipantAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ParticipantAddress) > 0 {
		i -= len(m.ParticipantAddress)
		copy(dAtA[i:], m.ParticipantAddress)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ParticipantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPocV2(dAtA []byte, offset int, v uint64) int {
	offset -= sovPocV2(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PoCArtifactV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovPocV2(uint64(m.Nonce))
	}
	l = len(m.Vector)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	return n
}

func (m *PoCBatchV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParticipantAddress)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.PocStageStartBlockHeight != 0 {
		n += 1 + sovPocV2(uint64(m.PocStageStartBlockHeight))
	}
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if len(m.Artifacts) > 0 {
		for _, e := range m.Artifacts {
			l = e.Size()
			n += 1 + l + sovPocV2(uint64(l))
		}
	}
	return n
}

func (m *PoCValidationV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParticipantAddress)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	l = len(m.ValidatorParticipantAddress)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.PocStageStartBlockHeight != 0 {
		n += 1 + sovPocV2(uint64(m.PocStageStartBlockHeight))
	}
	if m.ValidatedWeight != 0 {
		n += 1 + sovPocV2(uint64(m.ValidatedWeight))
	}
	return n
}

func sovPocV2(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPocV2(x uint64) (n int) {
	return sovPocV2(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PoCArtifactV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoCArtifactV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoCArtifactV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vector", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vector = append(m.Vector[:0], dAtA[iNdEx:postIndex]...)
			if m.Vector == nil {
				m.Vector = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoCBatchV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoCBatchV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoCBatchV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocStageStartBlockHeight", wireType)
			}
			m.PocStageStartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocStageStartBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Artifacts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Artifacts = append(m.Artifacts, &PoCArtifactV2{})
			if err := m.Artifacts[len(m.Artifacts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoCValidationV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoCValidationV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoCValidationV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocStageStartBlockHeight", wireType)
			}
			m.PocStageStartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocStageStartBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatedWeight", wireType)
			}
			m.ValidatedWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatedWeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPocV2(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPocV2
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPocV2
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPocV2
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPocV2        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPocV2          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPocV2 = fmt.Errorf("proto: unexpected end of group")
)
